version: '3.9'

services:
  web:
    container_name: api
    build:
      dockerfile: ./infra/rust/Dockerfile
      context: .
    ports:
      - ${API_PORT:-8080}:3000
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-local_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_pass}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-rust_practice}
    volumes:
      - ./api/frontend/public:/usr/src/app/public
    networks:
      - app_network

  db:
    container_name: postgres
    build:
      dockerfile: ./infra/postgres/Dockerfile
      context: .
    ports: 
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-local_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_pass}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_DB: ${POSTGRES_DB:-rust_practice}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
